server.port=8080
spring.application.name=tuniway-connect-back
spring.datasource.url=jdbc:postgresql://localhost:5432/tuniway_db
spring.datasource.username=tuniway_admin
spring.datasource.password=L30NSK3nNedY